[FIX] 에러 수정
throw new Error('callback function required');
    ^
Error: callback function required

throw new Error('callback function required');
    ^
Error: callback function required

const result = await postService.writePost(collection, post);
                                   ^
TypeError: postService.writePost is not a function